### ISSUE TITLE
Sprint 2 - Tarea 4 - Crear una interfaz para que el cliente visualice productos y seleccionar el de preferencia

### ISSUE THREAD

**Issue by know1988** [INGENIERIA-CREATIVA/Desarrollo_Web_Ciclo_4#5]
Es posible para el cliente visualizar los productos disponibles en el sistema y enviar al carrito los de su preferencia

**Comment by know1988** [comment]
![Image](https://user-images.githubusercontent.com/105815209/196814725-c03fc4d2-bef3-452d-bba4-8fee97092cf6.png)

**Comment by 42752263** [comment]
Actulizacion
